[accesslog]
[api]
dashboard = true
debug = true
insecure = true

[log]
level = "DEBUG"

[entryPoints]
[entryPoints.web]
address = ":80"
[entryPoints.ftp]
address = ":21"

#[entryPoints.websecure]
#address = ":443"
#[entryPoints.websecure.http.tls]
#
#[tls]
#[[tls.certificates]]
#certFile = "/etc/traefik/certs/bolt.local.crt"
#keyFile = "/etc/traefik/certs/bolt.local.key"

[providers.file]
directory = "/etc/traefik/conf.d/"
watch = true

[providers.docker]
endpoint = "unix:///var/run/docker.sock"
exposedByDefault = false
