[http]
[http.routers]
[http.routers.frontend-route]
entryPoints = ["web"]
priority = 4
rule = 'Host(`app.bolt.local`)'
service = "frontend"
#tls = true                      # Enable TLS for this router

[http.services]
[http.services.frontend]
[http.services.frontend.loadBalancer]
[[http.services.frontend.loadBalancer.servers]]
url = 'http://{{ env "BOLT_REMOTE_IP" }}:3000'
