[http]
[http.routers]
[http.routers.live-route]
entryPoints = ["web"]
rule = "Host(`live.{{ env 'BOLT_DOMAIN' }}.local`)"
service = "live"

[http.services]
[http.services.live]
[http.services.live.loadBalancer]
[[http.services.live.loadBalancer.servers]]
url = 'http://{{ env "BOLT_HOST" }}:5555'
