[http]
[http.routers]
[http.routers.live-route]
entryPoints = ["web"]
rule = 'Host(`live.bolt.local`)'
service = "live"
#tls = true                       # Enable TLS

[http.services]
[http.services.live]
[http.services.live.loadBalancer]
[[http.services.live.loadBalancer.servers]]
url = 'http://{{ env "BOLT_REMOTE_IP" }}:5555'
