[http]
[http.routers]
[http.routers.search-route]
entryPoints = ["web"]
rule = 'Host(`search.bolt.local`)'
service = "search"

[http.services]
[http.services.search]
[http.services.search.loadBalancer]
[[http.services.search.loadBalancer.servers]]
url = 'http://typesense:8108'
