from typing import List, Literal
from pydantic import BaseModel

from src.lib.ai_document.utils.ai_document_classes import SEGMENT_NAMES


class CoronaryTree(BaseModel):
    main: SEGMENT_NAMES
    parent: SEGMENT_NAMES
    children: List["CoronaryTree"]
    tree_type: Literal["main", "side"]

    class Config:
        # To handle recursive references
        arbitrary_types_allowed = True


LAD_tree = [
    CoronaryTree(
        main="LAD1_ostium",
        parent="LM_distal",
        tree_type="side",
        children=[
            CoronaryTree(
                main="LAD1_proximal",
                parent="LAD1_ostium",
                tree_type="main",
                children=[
                    CoronaryTree(
                        main="LAD1_distal",
                        parent="LAD1_proximal",
                        tree_type="main",
                        children=[
                            CoronaryTree(
                                main="Sept1",
                                parent="LAD1_distal",
                                tree_type="side",
                                children=[],
                            ),
                            CoronaryTree(
                                main="LAD2_proximal",
                                parent="LAD1_distal",
                                tree_type="main",
                                children=[
                                    CoronaryTree(
                                        main="LAD2_distal",
                                        parent="LAD2_proximal",
                                        tree_type="main",
                                        children=[
                                            CoronaryTree(
                                                main="Diag2_ostium",
                                                parent="LAD2_distal",
                                                tree_type="main",
                                                children=[
                                                    CoronaryTree(
                                                        main="Diag2",
                                                        parent="Diag2_ostium",
                                                        tree_type="side",
                                                        children=[],
                                                    )
                                                ],
                                            ),
                                            CoronaryTree(
                                                main="LAD3_proximal",
                                                parent="LAD2_distal",
                                                tree_type="main",
                                                children=[
                                                    CoronaryTree(
                                                        main="LAD3_distal",
                                                        parent="LAD3_proximal",
                                                        tree_type="main",
                                                        children=[],
                                                    )
                                                ],
                                            ),
                                            CoronaryTree(
                                                main="Sept2",
                                                parent="LAD2_distal",
                                                tree_type="main",
                                                children=[],
                                            ),
                                        ],
                                    ),
                                    CoronaryTree(
                                        main="Diag1_ostium",
                                        parent="LAD2_proximal",
                                        tree_type="side",
                                        children=[
                                            CoronaryTree(
                                                main="Diag1",
                                                parent="Diag1_ostium",
                                                tree_type="main",
                                                children=[],
                                            )
                                        ],
                                    ),
                                ],
                            ),
                        ],
                    )
                ],
            )
        ],
    ),
]

bisec_tree = [
    CoronaryTree(
        main="Bisec_ostium",
        parent="LM_distal",
        tree_type="side",
        children=[
            CoronaryTree(
                main="Bisec_proximal",
                parent="Bisec_ostium",
                tree_type="main",
                children=[
                    CoronaryTree(
                        main="Bisec_distal",
                        parent="Bisec_proximal",
                        tree_type="main",
                        children=[],
                    )
                ],
            )
        ],
    ),
]


CX_tree = [
    CoronaryTree(
        main="CX1_ostium",
        parent="LM_distal",
        tree_type="side",
        children=[
            CoronaryTree(
                main="CX1_proximal",
                parent="CX1_ostium",
                tree_type="main",
                children=[
                    CoronaryTree(
                        main="CX1_distal",
                        parent="CX1_proximal",
                        tree_type="main",
                        children=[
                            CoronaryTree(
                                main="Marg1_ostium",
                                parent="CX1_distal",
                                tree_type="side",
                                children=[
                                    CoronaryTree(
                                        main="Marg1_proximal",
                                        parent="Marg1_ostium",
                                        tree_type="main",
                                        children=[
                                            CoronaryTree(
                                                main="Marg1_distal",
                                                parent="Marg1_proximal",
                                                tree_type="main",
                                                children=[],
                                            )
                                        ],
                                    )
                                ],
                            ),
                            CoronaryTree(
                                main="CX2_proximal",
                                parent="CX1_distal",
                                tree_type="main",
                                children=[
                                    CoronaryTree(
                                        main="Marg2_ostium",
                                        parent="CX2_proximal",
                                        tree_type="side",
                                        children=[
                                            CoronaryTree(
                                                main="Marg2_proximal",
                                                parent="Marg2_ostium",
                                                tree_type="main",
                                                children=[
                                                    CoronaryTree(
                                                        main="Marg2_distal",
                                                        parent="Marg2_proximal",
                                                        tree_type="main",
                                                        children=[],
                                                    )
                                                ],
                                            )
                                        ],
                                    ),
                                    CoronaryTree(
                                        main="CX2_distal",
                                        parent="CX2_proximal",
                                        tree_type="main",
                                        children=[
                                            CoronaryTree(
                                                main="CX3_proximal",
                                                parent="CX2_distal",
                                                tree_type="main",
                                                children=[
                                                    CoronaryTree(
                                                        main="CX3_distal",
                                                        parent="CX3_proximal",
                                                        tree_type="main",
                                                        children=[],
                                                    )
                                                ],
                                            ),
                                            CoronaryTree(
                                                main="IVPL_ostium",
                                                parent="CX2_distal",
                                                tree_type="side",
                                                children=[
                                                    CoronaryTree(
                                                        main="IVPL_proximal",
                                                        parent="IVPL_ostium",
                                                        tree_type="main",
                                                        children=[
                                                            CoronaryTree(
                                                                main="IVPL_distal",
                                                                parent="IVPL_proximal",
                                                                tree_type="main",
                                                                children=[],
                                                            )
                                                        ],
                                                    )
                                                ],
                                            ),
                                        ],
                                    ),
                                ],
                            ),
                        ],
                    )
                ],
            )
        ],
    ),
]
LM_tree = [
    CoronaryTree(
        main="LM_proximal",
        parent="LM_proximal",
        tree_type="main",
        children=[
            CoronaryTree(
                main="LM_medium",
                parent="LM_proximal",
                tree_type="main",
                children=[
                    CoronaryTree(
                        main="LM_distal",
                        parent="LM_medium",
                        tree_type="main",
                        children=[*LAD_tree, *bisec_tree, *CX_tree],
                    )
                ],
            )
        ],
    ),
]
RCD_tree = [
    CoronaryTree(
        main="CD1_ostium",
        parent="CD1_ostium",
        tree_type="main",
        children=[
            CoronaryTree(
                main="CD1_proximal",
                parent="CD1_ostium",
                tree_type="main",
                children=[
                    CoronaryTree(
                        main="CD1_distal",
                        parent="CD1_proximal",
                        tree_type="main",
                        children=[
                            CoronaryTree(
                                main="MargR2",
                                parent="CD1_distal",
                                tree_type="side",
                                children=[],
                            ),
                            CoronaryTree(
                                main="CD2_proximal",
                                parent="CD1_distal",
                                tree_type="main",
                                children=[
                                    CoronaryTree(
                                        main="CD2_distal",
                                        parent="CD2_proximal",
                                        tree_type="main",
                                        children=[
                                            CoronaryTree(
                                                main="IVPR_ostium",
                                                parent="CD2_distal",
                                                tree_type="side",
                                                children=[
                                                    CoronaryTree(
                                                        main="IVPR_proximal",
                                                        parent="IVPR_ostium",
                                                        tree_type="main",
                                                        children=[
                                                            CoronaryTree(
                                                                main="IVPR_distal",
                                                                parent="IVPR_proximal",
                                                                tree_type="main",
                                                                children=[],
                                                            )
                                                        ],
                                                    )
                                                ],
                                            ),
                                            CoronaryTree(
                                                main="RVG_ostium",
                                                parent="CD2_distal",
                                                tree_type="side",
                                                children=[
                                                    CoronaryTree(
                                                        main="RVG_proximal",
                                                        parent="RVG_ostium",
                                                        tree_type="main",
                                                        children=[
                                                            CoronaryTree(
                                                                main="RVG_distal",
                                                                parent="RVG_proximal",
                                                                tree_type="main",
                                                                children=[],
                                                            )
                                                        ],
                                                    )
                                                ],
                                            ),
                                        ],
                                    )
                                ],
                            ),
                        ],
                    ),
                    CoronaryTree(
                        main="MargR1",
                        parent="CD1_proximal",
                        tree_type="side",
                        children=[],
                    ),
                ],
            )
        ],
    ),
]

coronary_tree = LM_tree + RCD_tree
