from src.lib.ai_document.utils.ai_document_classes import SEGMENT_NAMES


def segments_mapping(segment: SEGMENT_NAMES) -> str:
    segment_titles = {
        "Bisec_distal": "partie distale de la Bisectrice",
        "Bisec_ostium": "ostium de la bisectrice",
        "Bisec_proximal": "partie proximale de la Bisectrice",
        "CD1_distal": "partie distal de la coronaire droite proximale",
        "CD1_ostium": "ostium de la coronaire droite proximale",
        "CD1_proximal": "partie proximale de la coronaire droite proximale",
        "CD2_distal": "partie distale de la Coronaire droite moyenne",
        "CD2_proximal": "partie proximale de la coronaire droite moyenne",
        "CX1_distal": "partie distale de la circonflexe proximale",
        "CX1_ostium": "ostium de la circonflexe proximale",
        "CX1_proximal": "partie proximale de la circonflexe proximale",
        "CX2_distal": "partie distale de la circonflexe moyenne",
        "CX2_proximal": "partie proximale de la circonflexe moyenne",
        "CX3_distal": "partie distale de la circonflexe distale",
        "CX3_proximal": "partie proximale de la circonflex distale",
        "Diag1": "première diagonale diagonale",
        "Diag1_ostium": "ostium de la première diagonale",
        "Diag2": "deuxième diagonale",
        "Diag2_ostium": "ostium de la deuxième diagonale",
        "IVPL_distal": "interventriculaire postérieur gauche distale",
        "IVPL_ostium": "ostium de l'interventriculaire postérieur gauche",
        "IVPL_proximal": "partie proximale de l'interventriculaire postérieur gauche",
        "IVPR_distal": "partie distale de l'interventriculaire postérieur droite",
        "IVPR_ostium": "ostium de l'interventriculaire postérieur droite",
        "IVPR_proximal": "partie proximal l'interventriculaire postérieur droite",
        "LAD1_distal": "partie distale de l'interventriculaire antérieur proximale",
        "LAD1_ostium": "Ostium de l'interventriculaire antérieur proximale",
        "LAD1_proximal": "partie proximale de l'interventriculaire antérieur proximale",
        "LAD2_distal": "partie distale de l'interventriculaire antérieur moyenne",
        "LAD2_proximal": "partie proximale de l'interventriculaire antérieur moyenne",
        "LAD3_distal": "partie distale de l'interventriculaire antérieur distale",
        "LAD3_proximal": "partie proximale de l'interventriculaire antérieur distale",
        "LM_distal": "tronc commun gauche distal",
        "LM_medium": "tronc commun gauche moyen",
        "LM_proximal": "tronc commun gauche proximal",
        "Marg1_distal": "partie distale de la première marginale",
        "Marg1_ostium": "ostium de la première marginale",
        "Marg1_proximal": "partie proximale de la première marginale",
        "Marg2_distal": "partie distale de la deuxième marginale",
        "Marg2_ostium": "ostium de la deuxième marginale",
        "Marg2_proximal": "partie proximale de la deuxième marginale",
        "MargR1": "première marginale du bord droit",
        "MargR2": "deuxième marginale du bord droit",
        "RVG_distal": "rétro-ventriculaire gauche distale",
        "RVG_ostium": "ostium de la rétro-ventriculaire gauche",
        "RVG_proximal": "rétro-ventriculaire gauche proximale",
        "Sept1": "première septale",
        "Sept2": "deuxième septale",
    }

    return segment_titles.get(segment, "")
